name: Release Action Updated
description: GitHub Action to automatically release packages using lerna or semantic-release
author: remixie
inputs:
  github_token:
    description: GitHub Token used to create the release on GitHub and publish on GitHub registry.
    required: true
  npm_token:
    description: NPM token with publish permission. If not provided, publishing to npm registry will be skipped.
    required: false
  publish:
    description: Enable or disable publishing to package registries. When set to false, releases are only created on GitHub.
    default: true
    required: false
  push:
    description: Enable or disable pushing changes made by the action.
    default: true
    required: false
  name:
    description: User name to use when pushing to GitHub.
    default: github-actions[bot]
    required: false
  email:
    description: Email to use when pushing to GitHub.
    default: github-actions[bot]@users.noreply.github.com
    required: false
  message:
    description: Commit message to use when bumping package.json.
    default: 'ci(release): %s'
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: package
  color: purple
